### ISSUE TITLE
Hardcode left margin of header 'delete icon' on note card

### ISSUE THREAD

**Issue by parveen-sishodiya-git** [parveen-sishodiya-git/verbtile#1]
In this, there are note card and in header of this there is a delete icon on right side of it, which is placed force fully there to keep on right,
and when we change screen size to see the responsiveness then that icon get distorted,
there should be some auto float right.

![image](https://user-images.githubusercontent.com/68284243/95333205-18f41f00-08ca-11eb-94ef-f2a66f627696.png)

**Comment by parveen-sishodiya-git** [comment]
Updated label

**Comment by anushri20** [comment]
Hi, Can I work on this?

**Comment by parveen-sishodiya-git** [comment]
Why not anushri, please go ahead.

**Comment by anushri20** [comment]
@parveen-sishodiya-git I am not able to run this project properly, Do I need to install something?

**Comment by parveen-sishodiya-git** [comment]
No you don't need to install anything, but as the 'index.html' file contains bootstrap and jQuery **cdn path links** - you only need working internet connection while executing project.

Try in this way and ping me.

**Comment by parveen-sishodiya-git** [comment]
You should try this also:
Ensure that your bowser JavaScript is enabled in which you are running the project.

![image](https://user-images.githubusercontent.com/68284243/95467075-aa32c680-099a-11eb-99f5-7849b60a7587.png)

**Comment by anushri20** [comment]
Yaah It's working now, Thank you

**Comment by parveen-sishodiya-git** [comment]
Great 👍 : It has been perfect now, as it was noticeable icon in UI. Thankyou Anushri for your contribution to fix the issue.
